class FetchCoursesConstants:
    LINK_PD_COLUMNS = ['Courses', 'links', 'full_links']
    GET_COURSE_DETAILS_PD_COLUMNS = ['Courses', 'full_links']
    DEPARTMENT_PD_COLUMNS = ['department_id', 'department_name']
    COURSES_DESC_PD_COLUMNS = ['courses_id', 'course_name', 'department_id']

    COURSE_CATALOG_URL = "https://catalog.colorado.edu/courses-a-z/"
    COURSE_INFO_URL = "https://classes.colorado.edu/api/?page=fose&route=search"
    COURSE_DESCRIPTION_URL = "https://classes.colorado.edu/api/?page=fose&route=details"
    COURSE_CATALOG = ["Accounting (ACCT)", "Advertising, PR and Media Design (APRD)", "Aerospace Engineering (ASEN)",
                      "Air Force Aerospace Studies - ROTC (AIRR)", "Anthropology (ANTH)", "Applied Math (APPM)",
                      "Arabic Languages (ARAB)", "Architectural Engineering (AREN)", "Architecture (ARCH)",
                      "Art Film Studies (ARTF)", "Art History (ARTH)", "Arts and Sciences Courses (ARSC)",
                      "Art Studio and Non-Studio (ARTS)", "Asian Studies (ASIA)",
                      "Astrophysical and Planetary Sciences (ASTR)", "ATLAS (ATLS)",
                      "Atmospheric and Oceanic Sciences (ATOC)", "Baker Residential Academic Program (BAKR)",
                      "BCOR Applied Semester Experience (BASE)", "Biochemistry (BCHM)", "Biomedical Engineering (BMEN)",
                      "Business Administration (BADM)", "Business Core (BCOR)",
                      "Business Environment and Policy (BPOL)", "Business Law (BSLW)", "Business Minor (BUSM)",
                      "Career Services (CSVC)", "Center for Western Civilization (CWCV)",
                      "Center of the American West (CAMW)", "Central and East European Studies (CEES)",
                      "Chemical Engineering (CHEN)", "Chemistry (CHEM)", "Chinese (CHIN)",
                      "Cinema Studies & Moving Image Arts (CINE)", "Civil Engineering (CVEN)", "Classics (CLAS)",
                      "College of Engineering and Applied Science (COEN)",
                      "College of Media, Communication & Information (CMCI)", "Communication (COMM)",
                      "Communication Residential Academic Program (COMR)", "Comparative Literature (COML)",
                      "Computer Science (CSCI)", "Computer Science Post-Baccalaureate (CSPB)",
                      "Critical Media Practices (CMDP)", "Curriculum Emphasis in Social Responsibility (CESR)",
                      "Dance (DNCE)", "Danish (DANE)", "Digital Humanities (DHUM)",
                      "East Asian Languages and Civilizations (EALC)", "Ecology and Evolutionary Biology (EBIO)",
                      "Economics (ECON)", "Education (EDUC)", "Electrical and Computer Engineering (ECEN)",
                      "Energy Engineering (ENEN)", "Engineering, Ethics & Society (ENES)",
                      "Engineering for Developing Communities (EDEN)", "Engineering Honors (EHON)",
                      "Engineering Management (EMEN)", "Engineering Plus (GEEN)", "English as a Second Language (ESLG)",
                      "English (ENGL)", "Entrepreneurial and Small Business Management (ESBM)",
                      "Environmental Design (ENVD)", "Environmental Engineering (EVEN)",
                      "Environmental Product of Design (EPOD)", "Environmental Studies (ENVS)",
                      "Environment and Sustainability (ENST)", "Ethnic Studies (ETHN)", "Executive MBA (MBAE)",
                      "Experience Design (TDXD)", "Farrand Residential Academic Program (FARR)", "Farsi (FRSI)",
                      "Finance (FNCE)", "First Year Exploration (FYXP)", "First Year Seminar (FYSM)", "French (FREN)",
                      "Geography (GEOG)", "Geological Sciences (GEOL)", "German (GRMN)",
                      "Germanic and Slavic Languages and Literatures (GSLL)",
                      "Global Studies Residential Academic Program (GSAP)", "Graduate School (GRAD)",
                      "Graduate Teacher Education (GRTE)", "Greek Language (GREK)", "Hebrew (HEBR)",
                      "Hindi/Urdu (HIND)", "History (HIST)", "Honors (HONR)", "Humanities (HUMN)", "Indonesian (INDO)",
                      "Information Management and Business Analytics (BAIM)", "Information Science (INFO)",
                      "Integrative Physiology (IPHY)", "Intermedia Art, Writing and Performance (IAWP)",
                      "International Affairs (IAFS)", "International Business (INBU)", "INVST Community Studies (INVS)",
                      "Italian (ITAL)", "Japanese (JPNS)", "Jewish Studies (JWST)", "Journalism (JRNL)",
                      "Korean (KREN)", "Landscape Architecture (LAND)", "Language Technology (LGTC)",
                      "Latin American Studies (LAMS)", "Latin Language (LATN)", "Law School (LAWS)",
                      "Leadership Minor (LEAD)", "Lesbian, Gay and Bisexual Studies (LGBT)",
                      "Libby Residential Academic Program (LIBB)", "Libraries (LIBR)", "Linguistics (LING)",
                      "Management (MGMT)", "Marketing (MKTG)", "Master of the Environment (ENVM)",
                      "Materials Science and Engineering (MSEN)", "Mathematics (MATH)", "MBA Advanced Electives (MBAX)",
                      "MBA Core (MBAC)", "Mechanical Engineering (MCEN)", "Media Research and Practice (MDRP)",
                      "Media Studies (MDST)", "Medieval and Early Modern Studies (MEMS)",
                      "Military Science - Army ROTC (MILR)", "Molecular, Cellular and Developmental Biology (MCDB)",
                      "MS Business Core (MSBC)", "MS Business Electives (MSBX)", "Museum (MUSM)",
                      "Music Electives (MUEL)", "Music Ensemble (EMUS)", "Music (MUSC)", "Naval Science - ROTC (NAVR)",
                      "Neuroscience (NRSC)", "Norlin Scholars (NRLN)", "Operations and Information Management (OPIM)",
                      "Operations Management (OPMG)", "Organizational Leadership (ORGL)",
                      "Organization Management (ORMG)", "Outdoor Recreation (OREC)",
                      "Peace and Conflict Studies (PACS)", "Performance Music (PMUS)", "Philosophy (PHIL)",
                      "Physics (PHYS)", "Planning and Urban Design (PLAN)", "Political Science (PSCI)",
                      "Portuguese (PORT)", "Presidents Leadership Class (PRLC)", "Psychology (PSYC)",
                      "Real Estate (REAL)", "Religious Studies (RLST)", "Russian (RUSS)", "Sanskrit (SNSK)",
                      "Scandinavian (SCAN)", "Sewall Residential Academic Program (SEWL)", "Sociology (SOCY)",
                      "Spanish (SPAN)", "Speech, Language and Hearing Sciences (SLHS)", "Statistics (STAT)",
                      "Sustainability and Social Innovation Residential Academic Program (SSIR)", "Swedish (SWED)",
                      "Technology, Cybersecurity & Policy (CYBR)", "Telecommunications (TLEN)",
                      "Theatre and Dance (THDN)", "Theatre (THTR)", "Thesis Music (TMUS)", "Tibetan (TBTN)",
                      "Women and Gender Studies (WGST)", "Writing and Rhetoric (WRTG)", "Yiddish (YIDD)"]
