@startuml
!theme blueprint
actor       User              as User
participant FrontEnd          as FE
participant UserInfoService   as UIS
database    PostgreSQL        as PSQL

User -> FE   : Login using Email and Password
group Login
FE   -> UIS  : Email and Password Validation
UIS  -> PSQL : Fetch Password for Email
UIS  <- PSQL : Password
FE   <- UIS  : Authenticated
end

User -> FE   : Sign-in
group Sign-In
FE   -> UIS  : Store User Info
UIS  -> PSQL : Store User Info
UIS  <- PSQL : Store User Info
FE   <- UIS  : Successfully Stored
end

@enduml